server.port: 8080
spring:
  application:
    name: 未月拾叁
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  data:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: 8.136.110.151
    port: 5672
    username: guest
    password: guest

# mybatis-plus:
#   configuration:
#     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 自定义配置

config:
  redis:
    redisDeleteDelay: 100
  ipXbd:
    path: D:\IdeaProjects\blog\blog-server\ip2region.xdb
  log:
    path: D:\app2024-07-21.log
  global:
    env: dev
    index-name: 未月拾叁
    index-url: https://www.tsukiyo.cn
  jwt:
    secret: dsfsadawdasdasdaasd
